# Generated by Django 5.1.7 on 2025-05-21 08:32

import django.core.validators
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Community name')),
                ('description', models.TextField(max_length=450, verbose_name='Description')),
                ('banner', models.ImageField(blank=True, default='uploads/community/icons/default_icon.png', null=True, upload_to='uploads/community/banners/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'jpeg'))], verbose_name='Banner')),
                ('icon', models.ImageField(blank=True, default='uploads/community/icons/default_icon.png', null=True, upload_to='uploads/community/icons/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'jpeg'))], verbose_name='Icon')),
                ('is_nsfw', models.BooleanField(default=False, verbose_name='is_NSFW')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=10, verbose_name='Visibility')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='PB', max_length=10, verbose_name='Community status')),
                ('categories', mptt.fields.TreeManyToManyField(related_name='communities', to='categories.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
                'db_table': 'api_network_community',
                'ordering': ('created',),
            },
        ),
    ]
