# Generated by Django 5.2.9 on 2025-12-20 13:10

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities_created', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['-created'], name='api_network_created_760ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['-members_count', '-id'], name='api_network_members_31d54b_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['-activity_score', '-members_count', '-id'], name='api_network_activit_0693b1_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('name', config='english'), name='community_search_vector_idx'),
        ),
    ]
