# Generated by Django 5.1.7 on 2025-05-21 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities_created', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['slug', 'visibility'], name='api_network_slug_3051d7_idx'),
        ),
    ]
