# Generated by Django 5.1.7 on 2025-07-23 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(max_length=420, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=21, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Community name'),
        ),
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='URL'),
        ),
    ]
