# Generated by Django 5.1.7 on 2025-07-23 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_description_alter_community_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=21, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(message='Name can contain only letters, numbers, and underscores.', regex='^[A-Za-zА-Яа-яЁё0-9_]+$')], verbose_name='Community name'),
        ),
    ]
