# Generated by Django 5.1.7 on 2025-07-23 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('communities', '0004_alter_community_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='community',
            name='api_network_slug_3051d7_idx',
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['name', 'slug', 'visibility'], name='api_network_name_d46b1a_idx'),
        ),
    ]
