# Generated by Django 5.1.7 on 2025-07-24 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_remove_community_api_network_name_d46b1a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(max_length=420, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Description'),
        ),
    ]
