# Generated by Django 5.1.7 on 2025-07-24 22:30

import apps.services.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_alter_community_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, default='uploads/community/icons/default_icon.png', null=True, upload_to='uploads/community/banners/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'jpeg', 'webp')), apps.services.utils.MimeTypeValidator(allowed_types_keys=['image']), apps.services.utils.FileSizeValidator(max_size_mb=10)], verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='community',
            name='icon',
            field=models.ImageField(blank=True, default='uploads/community/icons/default_icon.png', null=True, upload_to='uploads/community/icons/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'jpeg', 'webp')), apps.services.utils.MimeTypeValidator(allowed_types_keys=['image']), apps.services.utils.FileSizeValidator(max_size_mb=7)], verbose_name='Icon'),
        ),
    ]
