# Generated by Django 5.1.7 on 2025-07-25 14:06

import apps.services.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_alter_community_banner_alter_community_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='icon',
            field=models.FileField(blank=True, default='uploads/community/icons/default_icon.png', null=True, upload_to='uploads/community/icons/%Y/%m/%d', validators=[apps.services.utils.MimeTypeValidator(
                allowed_mime_types=['image']), apps.services.utils.FileSizeValidator(max_size_mb=7), django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'jpeg', 'webp'))], verbose_name='Icon'),
        ),
    ]
