# Generated by Django 5.2.9 on 2025-12-20 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Joined at')),
                ('role', models.CharField(choices=[('CREATOR', 'Creator'), ('MODERATOR', 'Moderator'), ('MEMBER', 'Member')], default='MEMBER', max_length=20, verbose_name='Role')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='communities.community', verbose_name='Community')),
            ],
            options={
                'verbose_name': 'Community member',
                'verbose_name_plural': 'Community members',
                'db_table': 'api_network_membership',
                'ordering': ['-joined_at'],
            },
        ),
    ]
