# Generated by Django 5.1.7 on 2025-07-18 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
        ('memberships', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Community member', 'verbose_name_plural': 'Community members'},
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_moderator',
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'Creator'), ('MODERATOR', 'Moderator'), ('MEMBER', 'Member')], default='MEMBER', max_length=20, verbose_name='Role'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['community', 'role'], name='api_network_communi_992c88_idx'),
        ),
    ]
