services:
  api_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: api_backend:1.0.0
    container_name: api_backend_con
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /usr/src/api_backend
          ignore:
            - node_modules/
            - venv/
        - action: rebuild
          path: ./backend/requirements
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - ./backend/.env.dev
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:17-bookworm
    container_name: db
    volumes:
      - data:/var/lib/postgresql/data/
    restart: unless-stopped
    env_file:
      - ./backend/.env.dev
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: nextjs_frontend:1.0.0
    container_name: nextjs_frontend_con
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/src/frontend
          ignore:
            - venv/
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/package-lock.json
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - ./frontend/.env.dev
    command: npm run dev
    depends_on:
      - api_backend

volumes:
  data:
