# Generated by Django 5.2.9 on 2025-12-20 13:10

import apps.services.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('sum_rating', models.IntegerField(default=0, verbose_name='Rating sum')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'api_network_comment',
                'ordering': ('-time_created',),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm']), apps.services.utils.validate_file_size], verbose_name='File')),
                ('aspect_ratio', models.CharField(blank=True, default='16/9', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mediafile',
                'verbose_name_plural': 'Mediafiles',
                'db_table': 'api_network_media',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Post title')),
                ('slug', models.SlugField(blank=True, max_length=310, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', max_length=600, verbose_name='Post description')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='PB', max_length=10, verbose_name='Post status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('sum_rating', models.IntegerField(default=0, verbose_name='Rating sum')),
                ('comment_count', models.IntegerField(default=0, verbose_name='Comment count')),
                ('score', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'api_network_post',
                'ordering': ['-created'],
            },
        ),
    ]
