# Generated by Django 5.1.7 on 2025-06-10 09:55

import apps.services.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='uploads/media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'webp', 'mp4', 'webm']), apps.services.utils.validate_file_size], verbose_name='File'),
        ),
    ]
