# Generated by Django 5.1.7 on 2025-07-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_description_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['post', '-uploaded_at'], name='api_network_post_id_b24545_idx'),
        ),
    ]
