# Generated by Django 5.1.7 on 2025-04-25 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.IntegerField(choices=[(1, 'upvote'), (-1, 'downvote')], verbose_name='Rating value')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'api_network_rating',
                'ordering': ('-time_created',),
                'indexes': [models.Index(fields=['-time_created', 'value'], name='api_network_time_cr_a1915f_idx'), models.Index(fields=['content_type', 'object_id', '-time_created', 'value'], name='api_network_content_213274_idx'), models.Index(fields=['user', 'content_type', 'object_id'], name='api_network_user_id_f68ca6_idx')],
                'unique_together': {('content_type', 'object_id', 'user')},
            },
        ),
    ]
