FROM python:3.13.7-slim-bookworm

WORKDIR /usr/src/api_backend

RUN apt-get update && apt-get install -y \
    libpq-dev gcc python3-dev libmagic1 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir media

RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN sed -i 's/\r$//g' /usr/src/api_backend/entrypoint.dev.sh
RUN chmod +x /usr/src/api_backend/entrypoint.dev.sh

ENTRYPOINT [ "./entrypoint.dev.sh" ]