FROM python:3.13.7-slim-bookworm

WORKDIR /usr/src/apibackend

RUN apt-get update && apt-get install -y \
    libpq-dev gcc python3-dev libmagic1 libvips-dev libvips libvips-tools \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir media

RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN sed -i 's/\r$//g' /usr/src/apibackend/entrypoint.dev.sh
RUN chmod +x /usr/src/apibackend/entrypoint.dev.sh

ENTRYPOINT [ "./entrypoint.dev.sh" ]