# Generated by Django 5.1.6 on 2025-02-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Post description'),
        ),
    ]
