# Generated by Django 5.1.6 on 2025-02-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Post description'),
            preserve_default=False,
        ),
    ]
