# Generated by Django 5.1.7 on 2025-03-15 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Post title'),
        ),
    ]
