# Generated by Django 5.1.7 on 2025-03-16 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0010_alter_post_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'upvote'), (-1, 'downvote'), (0, 'neutral')], verbose_name='Rating value')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='social_network.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ('-time_created',),
                'indexes': [models.Index(fields=['-time_created', 'value'], name='social_netw_time_cr_037e1d_idx'), models.Index(fields=['post'], name='social_netw_post_id_29b6b4_idx'), models.Index(fields=['user'], name='social_netw_user_id_4e47e8_idx')],
                'unique_together': {('post', 'user', 'ip_address')},
            },
        ),
    ]
