# Generated by Django 5.1.7 on 2025-03-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0011_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
