# Generated by Django 5.1.7 on 2025-03-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0014_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(choices=[(1, 'upvote'), (-1, 'downvote')], verbose_name='Rating value'),
        ),
    ]
