# Generated by Django 5.1.7 on 2025-03-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0015_alter_rating_value'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='social_netw_post_id_29b6b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='social_netw_user_id_4e47e8_idx',
        ),
    ]
