# Generated by Django 5.1.7 on 2025-03-16 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0016_remove_rating_social_netw_post_id_29b6b4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Post title'),
        ),
    ]
