# Generated by Django 5.1.7 on 2025-03-19 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('social_network', '0017_alter_post_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='social_netw_time_cr_037e1d_idx',
        ),
        migrations.AddField(
            model_name='rating',
            name='content_type',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='rating',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=[
                               'content_type', 'object_id', '-time_created', 'value'], name='social_netw_content_1a96f9_idx'),
        ),
    ]
