# Generated by Django 5.1.7 on 2025-03-19 14:55

from django.db import migrations


def migrate_ratings(apps, schema_editor):
    Rating = apps.get_model('social_network', 'Rating')
    Post = apps.get_model('social_network', 'Post')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    PostContentType = ContentType.objects.get_for_model(Post)

    # Переносим данные из post в content_type и object_id
    for rating in Rating.objects.all():
        if hasattr(rating, 'post_id') and rating.post_id:
            rating.content_type = PostContentType
            rating.object_id = rating.post_id
            rating.save()


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0018_remove_rating_social_netw_time_cr_037e1d_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_ratings)
    ]
