# Generated by Django 5.1.7 on 2025-03-19 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clean_null_ratings(apps, schema_editor):
    Rating = apps.get_model('social_network', 'Rating')
    # Удаляем строки, где content_type или object_id равны NULL
    Rating.objects.filter(content_type__isnull=True).delete()
    Rating.objects.filter(object_id__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('social_network', '0019_auto_20250319_1755'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('content_type', 'object_id', 'user')},
        ),
        # Добавляем очистку перед изменением полей
        migrations.RunPython(clean_null_ratings),
        migrations.AlterField(
            model_name='rating',
            name='content_type',
            field=models.ForeignKey(
                on_delete=models.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(
                fields=['-time_created', 'value'], name='social_netw_time_cr_037e1d_idx'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='post',
        ),
    ]
