# Generated by Django 5.1.7 on 2025-03-20 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('social_network', '0020_alter_rating_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='social_netw_user_id_2715f8_idx'),
        ),
    ]
