# Generated by Django 5.1.7 on 2025-03-22 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0021_rating_social_netw_user_id_2715f8_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
