# Generated by Django 5.1.7 on 2025-03-22 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0022_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
