# Generated by Django 5.1.7 on 2025-03-25 18:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0023_alter_post_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Community name')),
                ('description', models.TextField(max_length=450, verbose_name='Description')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='uploads/community/banners/%Y/%m/%d', verbose_name='Banner')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='uploads/community/icons/%Y/%m/%d', verbose_name='Icon')),
                ('is_nsfw', models.BooleanField(default=False, verbose_name='is_NSFW')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=10, verbose_name='Visibility')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='PB', max_length=10, verbose_name='Community status')),
                ('categories', models.ManyToManyField(related_name='communities', to='social_network.category', verbose_name='Categories')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Comunities',
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social_network.community'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['slug', 'visibility'], name='social_netw_slug_f78cba_idx'),
        ),
    ]
