# Generated by Django 5.1.7 on 2025-03-26 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0024_community_post_community_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Moderator')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved user')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined at')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='social_network.community', verbose_name='Community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Community member',
                'verbose_name_plural': 'Community members',
                'unique_together': {('user', 'community')},
            },
        ),
    ]
