# Generated by Django 5.1.7 on 2025-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0025_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, default='uploads/avatars/default.png', null=True, upload_to='uploads/community/banners/%Y/%m/%d', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='community',
            name='icon',
            field=models.ImageField(blank=True, default='uploads/avatars/default.png', null=True, upload_to='uploads/community/icons/%Y/%m/%d', verbose_name='Icon'),
        ),
    ]
