# Generated by Django 5.1.7 on 2025-03-28 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0026_alter_community_banner_alter_community_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ('created',), 'verbose_name': 'Community', 'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, default='uploads/avatars/default.png', null=True, upload_to='uploads/community/banners/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'jpeg'))], verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='community',
            name='icon',
            field=models.ImageField(blank=True, default='uploads/avatars/default.png', null=True, upload_to='uploads/community/icons/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'jpeg'))], verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Community name'),
        ),
    ]
