# Generated by Django 5.1.7 on 2025-03-29 14:57

import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0027_alter_community_options_alter_community_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='community',
            name='categories',
            field=mptt.fields.TreeManyToManyField(related_name='communities', to='social_network.category', verbose_name='Categories'),
        ),
    ]
