# Generated by Django 5.1.7 on 2025-03-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0028_remove_post_category_alter_community_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Joined at'),
        ),
    ]
