# Generated by Django 5.1.7 on 2025-04-04 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0029_alter_membership_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='icon',
            field=models.ImageField(blank=True, default='media/uploads/community/icons/default_icon.jpg', null=True, upload_to='uploads/community/icons/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'jpeg'))], verbose_name='Icon'),
        ),
    ]
