# Generated by Django 5.1.7 on 2025-04-04 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0034_alter_community_banner_alter_community_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, default='uploads/community/icons/default_icon.png', null=True, upload_to='uploads/community/banners/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'jpeg'))], verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='community',
            name='icon',
            field=models.ImageField(blank=True, default='uploads/community/icons/default_icon.png', null=True, upload_to='uploads/community/icons/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'jpeg'))], verbose_name='Icon'),
        ),
    ]
