# Generated by Django 5.1.7 on 2025-04-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0035_alter_community_banner_alter_community_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
